# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syringeController.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.s1_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.s1_groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_groupBox.sizePolicy().hasHeightForWidth())
        self.s1_groupBox.setSizePolicy(sizePolicy)
        self.s1_groupBox.setObjectName("s1_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.s1_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.jogBackBtn_1 = QtWidgets.QPushButton(self.s1_groupBox)
        self.jogBackBtn_1.setObjectName("jogBackBtn_1")
        self.verticalLayout.addWidget(self.jogBackBtn_1)
        self.jogFwdBtn_1 = QtWidgets.QPushButton(self.s1_groupBox)
        self.jogFwdBtn_1.setObjectName("jogFwdBtn_1")
        self.verticalLayout.addWidget(self.jogFwdBtn_1)
        self.disableBtn_1 = QtWidgets.QPushButton(self.s1_groupBox)
        self.disableBtn_1.setObjectName("disableBtn_1")
        self.verticalLayout.addWidget(self.disableBtn_1)
        self.line = QtWidgets.QFrame(self.s1_groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.startMove_1 = QtWidgets.QPushButton(self.s1_groupBox)
        self.startMove_1.setObjectName("startMove_1")
        self.verticalLayout.addWidget(self.startMove_1)
        self.stopMove_1 = QtWidgets.QPushButton(self.s1_groupBox)
        self.stopMove_1.setObjectName("stopMove_1")
        self.verticalLayout.addWidget(self.stopMove_1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.rateLbl_1 = QtWidgets.QLabel(self.s1_groupBox)
        self.rateLbl_1.setObjectName("rateLbl_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rateLbl_1)
        self.rate_1 = QtWidgets.QDoubleSpinBox(self.s1_groupBox)
        self.rate_1.setMaximum(9999.0)
        self.rate_1.setObjectName("rate_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rate_1)
        self.amtLbl_1 = QtWidgets.QLabel(self.s1_groupBox)
        self.amtLbl_1.setObjectName("amtLbl_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.amtLbl_1)
        self.duration_1 = QtWidgets.QDoubleSpinBox(self.s1_groupBox)
        self.duration_1.setObjectName("duration_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.duration_1)
        self.diamLbl_1 = QtWidgets.QLabel(self.s1_groupBox)
        self.diamLbl_1.setObjectName("diamLbl_1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.diamLbl_1)
        self.syringeDiam_1 = QtWidgets.QDoubleSpinBox(self.s1_groupBox)
        self.syringeDiam_1.setDecimals(3)
        self.syringeDiam_1.setProperty("value", 3.46)
        self.syringeDiam_1.setObjectName("syringeDiam_1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.syringeDiam_1)
        self.verticalLayout.addLayout(self.formLayout)
        self.retractAtEnd_1 = QtWidgets.QGroupBox(self.s1_groupBox)
        self.retractAtEnd_1.setFlat(False)
        self.retractAtEnd_1.setCheckable(True)
        self.retractAtEnd_1.setChecked(True)
        self.retractAtEnd_1.setObjectName("retractAtEnd_1")
        self.formLayout_6 = QtWidgets.QFormLayout(self.retractAtEnd_1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtWidgets.QLabel(self.retractAtEnd_1)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.retractAmt_1 = QtWidgets.QDoubleSpinBox(self.retractAtEnd_1)
        self.retractAmt_1.setObjectName("retractAmt_1")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.retractAmt_1)
        self.verticalLayout.addWidget(self.retractAtEnd_1)
        self.notes_1 = QtWidgets.QPlainTextEdit(self.s1_groupBox)
        self.notes_1.setObjectName("notes_1")
        self.verticalLayout.addWidget(self.notes_1)
        self.moveProgress_1 = QtWidgets.QProgressBar(self.s1_groupBox)
        self.moveProgress_1.setProperty("value", 0)
        self.moveProgress_1.setObjectName("moveProgress_1")
        self.verticalLayout.addWidget(self.moveProgress_1)
        self.horizontalLayout.addWidget(self.s1_groupBox)
        self.s2_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_groupBox.sizePolicy().hasHeightForWidth())
        self.s2_groupBox.setSizePolicy(sizePolicy)
        self.s2_groupBox.setObjectName("s2_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.s2_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.jogBackBtn_2 = QtWidgets.QPushButton(self.s2_groupBox)
        self.jogBackBtn_2.setObjectName("jogBackBtn_2")
        self.verticalLayout_2.addWidget(self.jogBackBtn_2)
        self.jogFwdBtn_2 = QtWidgets.QPushButton(self.s2_groupBox)
        self.jogFwdBtn_2.setObjectName("jogFwdBtn_2")
        self.verticalLayout_2.addWidget(self.jogFwdBtn_2)
        self.disableBtn_2 = QtWidgets.QPushButton(self.s2_groupBox)
        self.disableBtn_2.setObjectName("disableBtn_2")
        self.verticalLayout_2.addWidget(self.disableBtn_2)
        self.line_2 = QtWidgets.QFrame(self.s2_groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.startMove_2 = QtWidgets.QPushButton(self.s2_groupBox)
        self.startMove_2.setObjectName("startMove_2")
        self.verticalLayout_2.addWidget(self.startMove_2)
        self.stopMove_2 = QtWidgets.QPushButton(self.s2_groupBox)
        self.stopMove_2.setObjectName("stopMove_2")
        self.verticalLayout_2.addWidget(self.stopMove_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.s2_groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.rate_2 = QtWidgets.QDoubleSpinBox(self.s2_groupBox)
        self.rate_2.setMaximum(9999.0)
        self.rate_2.setObjectName("rate_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rate_2)
        self.amtLbl_2 = QtWidgets.QLabel(self.s2_groupBox)
        self.amtLbl_2.setObjectName("amtLbl_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.amtLbl_2)
        self.duration_2 = QtWidgets.QDoubleSpinBox(self.s2_groupBox)
        self.duration_2.setObjectName("duration_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.duration_2)
        self.diamLbl_2 = QtWidgets.QLabel(self.s2_groupBox)
        self.diamLbl_2.setObjectName("diamLbl_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.diamLbl_2)
        self.syringeDiam_2 = QtWidgets.QDoubleSpinBox(self.s2_groupBox)
        self.syringeDiam_2.setDecimals(3)
        self.syringeDiam_2.setProperty("value", 3.46)
        self.syringeDiam_2.setObjectName("syringeDiam_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.syringeDiam_2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.retractAtEnd_2 = QtWidgets.QGroupBox(self.s2_groupBox)
        self.retractAtEnd_2.setFlat(False)
        self.retractAtEnd_2.setCheckable(True)
        self.retractAtEnd_2.setChecked(True)
        self.retractAtEnd_2.setObjectName("retractAtEnd_2")
        self.formLayout_7 = QtWidgets.QFormLayout(self.retractAtEnd_2)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_7 = QtWidgets.QLabel(self.retractAtEnd_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.retractAmt_2 = QtWidgets.QDoubleSpinBox(self.retractAtEnd_2)
        self.retractAmt_2.setObjectName("retractAmt_2")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.retractAmt_2)
        self.verticalLayout_2.addWidget(self.retractAtEnd_2)
        self.notes_2 = QtWidgets.QPlainTextEdit(self.s2_groupBox)
        self.notes_2.setObjectName("notes_2")
        self.verticalLayout_2.addWidget(self.notes_2)
        self.moveProgress_2 = QtWidgets.QProgressBar(self.s2_groupBox)
        self.moveProgress_2.setProperty("value", 0)
        self.moveProgress_2.setObjectName("moveProgress_2")
        self.verticalLayout_2.addWidget(self.moveProgress_2)
        self.horizontalLayout.addWidget(self.s2_groupBox)
        self.s3_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s3_groupBox.sizePolicy().hasHeightForWidth())
        self.s3_groupBox.setSizePolicy(sizePolicy)
        self.s3_groupBox.setObjectName("s3_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.s3_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.jogBackBtn_3 = QtWidgets.QPushButton(self.s3_groupBox)
        self.jogBackBtn_3.setObjectName("jogBackBtn_3")
        self.verticalLayout_4.addWidget(self.jogBackBtn_3)
        self.jogFwdBtn_3 = QtWidgets.QPushButton(self.s3_groupBox)
        self.jogFwdBtn_3.setObjectName("jogFwdBtn_3")
        self.verticalLayout_4.addWidget(self.jogFwdBtn_3)
        self.disableBtn_3 = QtWidgets.QPushButton(self.s3_groupBox)
        self.disableBtn_3.setObjectName("disableBtn_3")
        self.verticalLayout_4.addWidget(self.disableBtn_3)
        self.line_3 = QtWidgets.QFrame(self.s3_groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.startMove_3 = QtWidgets.QPushButton(self.s3_groupBox)
        self.startMove_3.setObjectName("startMove_3")
        self.verticalLayout_4.addWidget(self.startMove_3)
        self.stopMove_3 = QtWidgets.QPushButton(self.s3_groupBox)
        self.stopMove_3.setObjectName("stopMove_3")
        self.verticalLayout_4.addWidget(self.stopMove_3)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.s3_groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.rate_3 = QtWidgets.QDoubleSpinBox(self.s3_groupBox)
        self.rate_3.setMaximum(9999.0)
        self.rate_3.setObjectName("rate_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rate_3)
        self.amtLbl_3 = QtWidgets.QLabel(self.s3_groupBox)
        self.amtLbl_3.setObjectName("amtLbl_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.amtLbl_3)
        self.duration_3 = QtWidgets.QDoubleSpinBox(self.s3_groupBox)
        self.duration_3.setObjectName("duration_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.duration_3)
        self.diamLbl_3 = QtWidgets.QLabel(self.s3_groupBox)
        self.diamLbl_3.setObjectName("diamLbl_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.diamLbl_3)
        self.syringeDiam_3 = QtWidgets.QDoubleSpinBox(self.s3_groupBox)
        self.syringeDiam_3.setDecimals(3)
        self.syringeDiam_3.setProperty("value", 3.46)
        self.syringeDiam_3.setObjectName("syringeDiam_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.syringeDiam_3)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.retractAtEnd_3 = QtWidgets.QGroupBox(self.s3_groupBox)
        self.retractAtEnd_3.setFlat(False)
        self.retractAtEnd_3.setCheckable(True)
        self.retractAtEnd_3.setChecked(True)
        self.retractAtEnd_3.setObjectName("retractAtEnd_3")
        self.formLayout_8 = QtWidgets.QFormLayout(self.retractAtEnd_3)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_8 = QtWidgets.QLabel(self.retractAtEnd_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.retractAmt_3 = QtWidgets.QDoubleSpinBox(self.retractAtEnd_3)
        self.retractAmt_3.setObjectName("retractAmt_3")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.retractAmt_3)
        self.verticalLayout_4.addWidget(self.retractAtEnd_3)
        self.notes_3 = QtWidgets.QPlainTextEdit(self.s3_groupBox)
        self.notes_3.setObjectName("notes_3")
        self.verticalLayout_4.addWidget(self.notes_3)
        self.moveProgress_3 = QtWidgets.QProgressBar(self.s3_groupBox)
        self.moveProgress_3.setProperty("value", 0)
        self.moveProgress_3.setObjectName("moveProgress_3")
        self.verticalLayout_4.addWidget(self.moveProgress_3)
        self.horizontalLayout.addWidget(self.s3_groupBox)
        self.s4_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.s4_groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4_groupBox.sizePolicy().hasHeightForWidth())
        self.s4_groupBox.setSizePolicy(sizePolicy)
        self.s4_groupBox.setObjectName("s4_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.s4_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.jogBackBtn_4 = QtWidgets.QPushButton(self.s4_groupBox)
        self.jogBackBtn_4.setObjectName("jogBackBtn_4")
        self.verticalLayout_3.addWidget(self.jogBackBtn_4)
        self.jogFwdBtn_4 = QtWidgets.QPushButton(self.s4_groupBox)
        self.jogFwdBtn_4.setObjectName("jogFwdBtn_4")
        self.verticalLayout_3.addWidget(self.jogFwdBtn_4)
        self.disableBtn_4 = QtWidgets.QPushButton(self.s4_groupBox)
        self.disableBtn_4.setObjectName("disableBtn_4")
        self.verticalLayout_3.addWidget(self.disableBtn_4)
        self.line_4 = QtWidgets.QFrame(self.s4_groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.startMove_4 = QtWidgets.QPushButton(self.s4_groupBox)
        self.startMove_4.setObjectName("startMove_4")
        self.verticalLayout_3.addWidget(self.startMove_4)
        self.stopMove_4 = QtWidgets.QPushButton(self.s4_groupBox)
        self.stopMove_4.setObjectName("stopMove_4")
        self.verticalLayout_3.addWidget(self.stopMove_4)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.s4_groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.rate_4 = QtWidgets.QDoubleSpinBox(self.s4_groupBox)
        self.rate_4.setMaximum(9999.0)
        self.rate_4.setObjectName("rate_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rate_4)
        self.amtLbl_4 = QtWidgets.QLabel(self.s4_groupBox)
        self.amtLbl_4.setObjectName("amtLbl_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.amtLbl_4)
        self.duration_4 = QtWidgets.QDoubleSpinBox(self.s4_groupBox)
        self.duration_4.setObjectName("duration_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.duration_4)
        self.diamLbl_4 = QtWidgets.QLabel(self.s4_groupBox)
        self.diamLbl_4.setObjectName("diamLbl_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.diamLbl_4)
        self.syringeDiam_4 = QtWidgets.QDoubleSpinBox(self.s4_groupBox)
        self.syringeDiam_4.setDecimals(3)
        self.syringeDiam_4.setProperty("value", 3.46)
        self.syringeDiam_4.setObjectName("syringeDiam_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.syringeDiam_4)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.retractAtEnd_4 = QtWidgets.QGroupBox(self.s4_groupBox)
        self.retractAtEnd_4.setFlat(False)
        self.retractAtEnd_4.setCheckable(True)
        self.retractAtEnd_4.setChecked(True)
        self.retractAtEnd_4.setObjectName("retractAtEnd_4")
        self.formLayout_9 = QtWidgets.QFormLayout(self.retractAtEnd_4)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_9 = QtWidgets.QLabel(self.retractAtEnd_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.retractAmt_4 = QtWidgets.QDoubleSpinBox(self.retractAtEnd_4)
        self.retractAmt_4.setObjectName("retractAmt_4")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.retractAmt_4)
        self.verticalLayout_3.addWidget(self.retractAtEnd_4)
        self.notes_4 = QtWidgets.QPlainTextEdit(self.s4_groupBox)
        self.notes_4.setObjectName("notes_4")
        self.verticalLayout_3.addWidget(self.notes_4)
        self.moveProgress_4 = QtWidgets.QProgressBar(self.s4_groupBox)
        self.moveProgress_4.setProperty("value", 0)
        self.moveProgress_4.setObjectName("moveProgress_4")
        self.verticalLayout_3.addWidget(self.moveProgress_4)
        self.horizontalLayout.addWidget(self.s4_groupBox)
        self.s5_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s5_groupBox.sizePolicy().hasHeightForWidth())
        self.s5_groupBox.setSizePolicy(sizePolicy)
        self.s5_groupBox.setObjectName("s5_groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.s5_groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.jogBackBtn_5 = QtWidgets.QPushButton(self.s5_groupBox)
        self.jogBackBtn_5.setObjectName("jogBackBtn_5")
        self.verticalLayout_5.addWidget(self.jogBackBtn_5)
        self.jogFwdBtn_5 = QtWidgets.QPushButton(self.s5_groupBox)
        self.jogFwdBtn_5.setObjectName("jogFwdBtn_5")
        self.verticalLayout_5.addWidget(self.jogFwdBtn_5)
        self.disableBtn_5 = QtWidgets.QPushButton(self.s5_groupBox)
        self.disableBtn_5.setObjectName("disableBtn_5")
        self.verticalLayout_5.addWidget(self.disableBtn_5)
        self.line_6 = QtWidgets.QFrame(self.s5_groupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_5.addWidget(self.line_6)
        self.startMove_5 = QtWidgets.QPushButton(self.s5_groupBox)
        self.startMove_5.setObjectName("startMove_5")
        self.verticalLayout_5.addWidget(self.startMove_5)
        self.stopMove_5 = QtWidgets.QPushButton(self.s5_groupBox)
        self.stopMove_5.setObjectName("stopMove_5")
        self.verticalLayout_5.addWidget(self.stopMove_5)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_5 = QtWidgets.QLabel(self.s5_groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.rate_5 = QtWidgets.QDoubleSpinBox(self.s5_groupBox)
        self.rate_5.setMaximum(9999.0)
        self.rate_5.setObjectName("rate_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rate_5)
        self.amtLbl_5 = QtWidgets.QLabel(self.s5_groupBox)
        self.amtLbl_5.setObjectName("amtLbl_5")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.amtLbl_5)
        self.duration_5 = QtWidgets.QDoubleSpinBox(self.s5_groupBox)
        self.duration_5.setObjectName("duration_5")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.duration_5)
        self.diamLbl_5 = QtWidgets.QLabel(self.s5_groupBox)
        self.diamLbl_5.setObjectName("diamLbl_5")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.diamLbl_5)
        self.syringeDiam_5 = QtWidgets.QDoubleSpinBox(self.s5_groupBox)
        self.syringeDiam_5.setDecimals(3)
        self.syringeDiam_5.setProperty("value", 3.46)
        self.syringeDiam_5.setObjectName("syringeDiam_5")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.syringeDiam_5)
        self.verticalLayout_5.addLayout(self.formLayout_5)
        self.retractAtEnd_5 = QtWidgets.QGroupBox(self.s5_groupBox)
        self.retractAtEnd_5.setFlat(False)
        self.retractAtEnd_5.setCheckable(True)
        self.retractAtEnd_5.setChecked(True)
        self.retractAtEnd_5.setObjectName("retractAtEnd_5")
        self.formLayout_10 = QtWidgets.QFormLayout(self.retractAtEnd_5)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_10 = QtWidgets.QLabel(self.retractAtEnd_5)
        self.label_10.setObjectName("label_10")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.retractAmt_5 = QtWidgets.QDoubleSpinBox(self.retractAtEnd_5)
        self.retractAmt_5.setObjectName("retractAmt_5")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.retractAmt_5)
        self.verticalLayout_5.addWidget(self.retractAtEnd_5)
        self.notes_5 = QtWidgets.QPlainTextEdit(self.s5_groupBox)
        self.notes_5.setObjectName("notes_5")
        self.verticalLayout_5.addWidget(self.notes_5)
        self.moveProgress_5 = QtWidgets.QProgressBar(self.s5_groupBox)
        self.moveProgress_5.setEnabled(True)
        self.moveProgress_5.setProperty("value", 0)
        self.moveProgress_5.setObjectName("moveProgress_5")
        self.verticalLayout_5.addWidget(self.moveProgress_5)
        self.horizontalLayout.addWidget(self.s5_groupBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.jogCtrlBox = QtWidgets.QGroupBox(self.centralwidget)
        self.jogCtrlBox.setFlat(False)
        self.jogCtrlBox.setCheckable(False)
        self.jogCtrlBox.setObjectName("jogCtrlBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.jogCtrlBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.jogCtrlBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.jogAmt = QtWidgets.QDoubleSpinBox(self.jogCtrlBox)
        self.jogAmt.setProperty("value", 10.0)
        self.jogAmt.setObjectName("jogAmt")
        self.horizontalLayout_10.addWidget(self.jogAmt)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.jogAllForwardBtn = QtWidgets.QPushButton(self.jogCtrlBox)
        self.jogAllForwardBtn.setObjectName("jogAllForwardBtn")
        self.verticalLayout_9.addWidget(self.jogAllForwardBtn)
        self.jogAllBackBtn = QtWidgets.QPushButton(self.jogCtrlBox)
        self.jogAllBackBtn.setObjectName("jogAllBackBtn")
        self.verticalLayout_9.addWidget(self.jogAllBackBtn)
        self.horizontalLayout_2.addWidget(self.jogCtrlBox)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.startAll_btn = QtWidgets.QPushButton(self.centralwidget)
        self.startAll_btn.setObjectName("startAll_btn")
        self.verticalLayout_7.addWidget(self.startAll_btn)
        self.stopAll_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stopAll_btn.setObjectName("stopAll_btn")
        self.verticalLayout_7.addWidget(self.stopAll_btn)
        self.disableAll_btn = QtWidgets.QPushButton(self.centralwidget)
        self.disableAll_btn.setObjectName("disableAll_btn")
        self.verticalLayout_7.addWidget(self.disableAll_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.portLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLabel.sizePolicy().hasHeightForWidth())
        self.portLabel.setSizePolicy(sizePolicy)
        self.portLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.portLabel.setObjectName("portLabel")
        self.horizontalLayout_3.addWidget(self.portLabel)
        self.portComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portComboBox.sizePolicy().hasHeightForWidth())
        self.portComboBox.setSizePolicy(sizePolicy)
        self.portComboBox.setObjectName("portComboBox")
        self.horizontalLayout_3.addWidget(self.portComboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.refreshBtn = QtWidgets.QPushButton(self.centralwidget)
        self.refreshBtn.setObjectName("refreshBtn")
        self.verticalLayout_8.addWidget(self.refreshBtn)
        self.connectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.connectBtn.setObjectName("connectBtn")
        self.verticalLayout_8.addWidget(self.connectBtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Config = QtWidgets.QAction(MainWindow)
        self.actionOpen_Config.setShortcutVisibleInContextMenu(True)
        self.actionOpen_Config.setObjectName("actionOpen_Config")
        self.actionSave_Config = QtWidgets.QAction(MainWindow)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen_Config)
        self.menuFile.addAction(self.actionSave_Config)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Electrospinning Controller"))
        self.s1_groupBox.setTitle(_translate("MainWindow", "Syringe 1"))
        self.jogBackBtn_1.setText(_translate("MainWindow", "Jog Back"))
        self.jogFwdBtn_1.setText(_translate("MainWindow", "Jog Forward"))
        self.disableBtn_1.setText(_translate("MainWindow", "Disable Motor"))
        self.startMove_1.setText(_translate("MainWindow", "Start Move"))
        self.stopMove_1.setText(_translate("MainWindow", "Stop Move"))
        self.rateLbl_1.setText(_translate("MainWindow", "Rate"))
        self.rate_1.setSuffix(_translate("MainWindow", " mL/hr"))
        self.amtLbl_1.setText(_translate("MainWindow", "Amount"))
        self.duration_1.setSuffix(_translate("MainWindow", " mL"))
        self.diamLbl_1.setText(_translate("MainWindow", "Syringe Size"))
        self.syringeDiam_1.setSuffix(_translate("MainWindow", " mm/mL"))
        self.retractAtEnd_1.setTitle(_translate("MainWindow", "Retract at end"))
        self.label_6.setText(_translate("MainWindow", "Amount"))
        self.retractAmt_1.setSuffix(_translate("MainWindow", " mm"))
        self.notes_1.setPlaceholderText(_translate("MainWindow", "Notes"))
        self.s2_groupBox.setTitle(_translate("MainWindow", "Syringe 2"))
        self.jogBackBtn_2.setText(_translate("MainWindow", "Jog Back"))
        self.jogFwdBtn_2.setText(_translate("MainWindow", "Jog Forward"))
        self.disableBtn_2.setText(_translate("MainWindow", "Disable Motor"))
        self.startMove_2.setText(_translate("MainWindow", "Start Move"))
        self.stopMove_2.setText(_translate("MainWindow", "Stop Move"))
        self.label_2.setText(_translate("MainWindow", "Rate"))
        self.rate_2.setSuffix(_translate("MainWindow", " mL/hr"))
        self.amtLbl_2.setText(_translate("MainWindow", "Amount"))
        self.duration_2.setSuffix(_translate("MainWindow", " mL"))
        self.diamLbl_2.setText(_translate("MainWindow", "Syringe Size"))
        self.syringeDiam_2.setSuffix(_translate("MainWindow", " mm/mL"))
        self.retractAtEnd_2.setTitle(_translate("MainWindow", "Retract at end"))
        self.label_7.setText(_translate("MainWindow", "Amount"))
        self.retractAmt_2.setSuffix(_translate("MainWindow", " mm"))
        self.notes_2.setPlaceholderText(_translate("MainWindow", "Notes"))
        self.s3_groupBox.setTitle(_translate("MainWindow", "Syringe 3"))
        self.jogBackBtn_3.setText(_translate("MainWindow", "Jog Back"))
        self.jogFwdBtn_3.setText(_translate("MainWindow", "Jog Forward"))
        self.disableBtn_3.setText(_translate("MainWindow", "Disable Motor"))
        self.startMove_3.setText(_translate("MainWindow", "Start Move"))
        self.stopMove_3.setText(_translate("MainWindow", "Stop Move"))
        self.label_3.setText(_translate("MainWindow", "Rate"))
        self.rate_3.setSuffix(_translate("MainWindow", " mL/hr"))
        self.amtLbl_3.setText(_translate("MainWindow", "Amount"))
        self.duration_3.setSuffix(_translate("MainWindow", " mL"))
        self.diamLbl_3.setText(_translate("MainWindow", "Syringe Size"))
        self.syringeDiam_3.setSuffix(_translate("MainWindow", " mm/mL"))
        self.retractAtEnd_3.setTitle(_translate("MainWindow", "Retract at end"))
        self.label_8.setText(_translate("MainWindow", "Amount"))
        self.retractAmt_3.setSuffix(_translate("MainWindow", " mm"))
        self.notes_3.setPlaceholderText(_translate("MainWindow", "Notes"))
        self.s4_groupBox.setTitle(_translate("MainWindow", "Syringe 4"))
        self.jogBackBtn_4.setText(_translate("MainWindow", "Jog Back"))
        self.jogFwdBtn_4.setText(_translate("MainWindow", "Jog Forward"))
        self.disableBtn_4.setText(_translate("MainWindow", "Disable Motor"))
        self.startMove_4.setText(_translate("MainWindow", "Start Move"))
        self.stopMove_4.setText(_translate("MainWindow", "Stop Move"))
        self.label_4.setText(_translate("MainWindow", "Rate"))
        self.rate_4.setSuffix(_translate("MainWindow", " mL/hr"))
        self.amtLbl_4.setText(_translate("MainWindow", "Amount"))
        self.duration_4.setSuffix(_translate("MainWindow", " mL"))
        self.diamLbl_4.setText(_translate("MainWindow", "Syringe Size"))
        self.syringeDiam_4.setSuffix(_translate("MainWindow", " mm/mL"))
        self.retractAtEnd_4.setTitle(_translate("MainWindow", "Retract at end"))
        self.label_9.setText(_translate("MainWindow", "Amount"))
        self.retractAmt_4.setSuffix(_translate("MainWindow", " mm"))
        self.notes_4.setPlaceholderText(_translate("MainWindow", "Notes"))
        self.s5_groupBox.setTitle(_translate("MainWindow", "Syringe 5"))
        self.jogBackBtn_5.setText(_translate("MainWindow", "Jog Back"))
        self.jogFwdBtn_5.setText(_translate("MainWindow", "Jog Forward"))
        self.disableBtn_5.setText(_translate("MainWindow", "Disable Motor"))
        self.startMove_5.setText(_translate("MainWindow", "Start Move"))
        self.stopMove_5.setText(_translate("MainWindow", "Stop Move"))
        self.label_5.setText(_translate("MainWindow", "Rate"))
        self.rate_5.setSuffix(_translate("MainWindow", " mL/hr"))
        self.amtLbl_5.setText(_translate("MainWindow", "Amount"))
        self.duration_5.setSuffix(_translate("MainWindow", " mL"))
        self.diamLbl_5.setText(_translate("MainWindow", "Syringe Size"))
        self.syringeDiam_5.setSuffix(_translate("MainWindow", " mm/mL"))
        self.retractAtEnd_5.setTitle(_translate("MainWindow", "Retract at end"))
        self.label_10.setText(_translate("MainWindow", "Amount"))
        self.retractAmt_5.setSuffix(_translate("MainWindow", " mm"))
        self.notes_5.setPlaceholderText(_translate("MainWindow", "Notes"))
        self.jogCtrlBox.setTitle(_translate("MainWindow", "Jog Controls"))
        self.label.setText(_translate("MainWindow", "Jog Amount"))
        self.jogAmt.setSuffix(_translate("MainWindow", " mm"))
        self.jogAllForwardBtn.setText(_translate("MainWindow", "Jog All Forwards"))
        self.jogAllBackBtn.setText(_translate("MainWindow", "Jog All Backwards"))
        self.startAll_btn.setText(_translate("MainWindow", "Start All Moves"))
        self.stopAll_btn.setText(_translate("MainWindow", "Stop All Moves"))
        self.disableAll_btn.setText(_translate("MainWindow", "Disable All Steppers"))
        self.portLabel.setText(_translate("MainWindow", "COM Port"))
        self.refreshBtn.setText(_translate("MainWindow", "Refresh Ports"))
        self.connectBtn.setText(_translate("MainWindow", "Connect"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Config.setText(_translate("MainWindow", "Open Config"))
        self.actionOpen_Config.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Config.setText(_translate("MainWindow", "Save Config"))
        self.actionSave_Config.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

